
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: node-app
spec:
  selector:
    app:node-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # Match the port where your Go application is running
      nodePort: 32002
