
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: node-app
spec:
  selector:
    app: node-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Match the port where your Go application is running
      nodePort: 32003